version: '3'

services:
  front:
    image: docker.dvladir.work/partners/dv-1/partners-ui:latest
    working_dir: /usr/src/app
    command: serve -s . -l 4200
    deploy:
      replicas: 1
  api:
    image: docker.dvladir.work/partners/dv-1/partners-api:latest
    working_dir: /usr/src/app
    command: java -jar app.jar
    volumes:
      - ./application.properties:/usr/src/app/application.properties
    deploy:
      replicas: 1
  nginx:
    image: docker.dvladir.work/library/nginx:stable-alpine
    ports:
      - "8083:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1