version: '3'

services:
  db:
    image: postgres:13-alpine3.14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - ./pg-main.env
    networks:
      - partners-network
  flyway:
    image: flyway/flyway:7.14.0-alpine
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
      - ./flyway.config:/flyway/conf/flyway.config
    depends_on:
      - db
    networks:
      - partners-network
  front:
    image: dvladir:partners-ui
    container_name: partners-ui
    working_dir: /usr/src/app
    command: serve -s . -l 4200
    restart: unless-stopped
    networks:
      - partners-network
  api:
    image: dvladir:partners-api
    container_name: partners-api
    working_dir: /usr/src/app
    command: yarn start:prod
    restart: unless-stopped
    volumes:
      - ./.env.production:/usr/src/app/.env.production
    networks:
      - partners-network
  nginx:
    image: nginx:stable-alpine
    container_name: partners-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - partners-network

networks:
  partners-network:
    driver: bridge