version: '3'

services:
  flyway:
    image: flyway/flyway:7.14.0-alpine
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./sql:/flyway/sql
      - ./flyway.config:/flyway/conf/flyway.config
    networks:
      - db-network
  front:
    image: dvladir:partners-ui
    container_name: partners-ui
    working_dir: /usr/src/app
    command: serve -s . -l 4200
    restart: unless-stopped
    networks:
      - partners-network
  api:
    image: dvladir:partners-api
    container_name: partners-api
    working_dir: /usr/src/app
    command: yarn start:prod
    restart: unless-stopped
    volumes:
      - ./.env.production:/usr/src/app/.env.production
    networks:
      - db-network
      - partners-network
  nginx:
    image: nginx:stable-alpine
    container_name: partners-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - partners-network

networks:
  db-network:
    external:
      name: db-network
  partners-network:
    driver: bridge