version: '3'

services:
  front:
    image: dvladir:partners-ui
    container_name: partners-ui
    working_dir: /usr/src/app
    command: serve -s . -l 4200
    restart: unless-stopped
    networks:
      - partners-network
    depends_on:
      - api
  api:
    image: dvladir:partners-api
    container_name: partners-api
    working_dir: /usr/src/app
    command: yarn start:prod
    restart: unless-stopped
    networks:
      - partners-network
  nginx:
    image: nginx:stable-alpine
    container_name: partners-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - partners-network
    depends_on:
      - api
      - front

networks:
  partners-network:
    driver: bridge