version: '3'

services:
  front:
    image: docker.dvladir.work/partners/dv-1/partners-ui:latest
    container_name: partners-ui
    working_dir: /usr/src/app
    command: serve -s . -l 4200
    restart: unless-stopped
    networks:
      - partners-network
    deploy:
      replicas: 2
  api:
    image: docker.dvladir.work/partners/dv-1/partners-api:latest
    container_name: partners-api
    working_dir: /usr/src/app
    command: java -jar app.jar
    restart: unless-stopped
    volumes:
      - ./application.properties:/usr/src/app/application.properties
    networks:
      - partners-network
    deploy:
      replicas: 2
  nginx:
    image: docker.dvladir.work/library/nginx:stable-alpine
    container_name: partners-nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - partners-network
    deploy:
      replicas: 2

networks:
  partners-network:
    driver: bridge